
services:
  test:
    build:
      context: ../../
      dockerfile: docker/unit_tests/dockerfile
    container_name: ragger
    command: > 
      bash -c "make test ./test/integration_tests || exit 1" 
      && docker-compose down
