FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

CMD ["bash"]

RUN apt-get update --fix-missing
RUN apt-get install -y python3 python3-pip git ca-certificates lsb-release ubuntu-keyring software-properties-common curl
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/opt/gtk/bin:$PATH"

RUN update-ca-certificates --fresh
RUN export SSL_CERT_DIR=/etc/ssl/certs
RUN apt install -y tesseract-ocr
RUN apt install -y libtesseract-dev
RUN apt install -y poppler-utils

WORKDIR /ragger
RUN pip install --upgrade pip
COPY . /ragger
RUN touch logs.log
RUN make install

RUN export GIT_PYTHON_GIT_EXECUTABLE=$(which git)
