FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

CMD ["bash"]

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /ragger
COPY . /ragger
RUN make install