
services:
  build_dev:
    build:
      context: ../../
      dockerfile: docker/build_dev/dockerfile
    volumes:
      - /home/runner/.cache/pip:/root/.cache/pip
      - /home/runner/.cache/pypoetry:/root/.cache/pypoetry
    command: ["poetry", "run", "pytest"]
    container_name: ragger
