name: Test

on: [push]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: docker-compose build

      - name: Run tests
        run: docker-compose run test
