name: Ragger Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: docker compose up -d setup
      - name: Test
        run: docker compose up -d test